# Configuration for Multi Agent Exploration

verbose: False
show_results: False
no_of_agents: 7
sensor_range: 45
# grid_len: 612
# grid_width: 612
complexity_level: 'very_easy' # very_easy,easy,moderate,difficult
